spring:
  profiles:
    active: production
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    show-sql: true
    format_sql: true
  datasource:
    url: jdbc:h2:mem:gdit
    username: SA
    password:
    driver-class-name: org.h2.Driver
---

spring:
  profiles:
    active: test
